"""Added telegram_chat_id to User model

Revision ID: 50b324dc058b
Revises: c943dd561f32
Create Date: 2025-02-12 01:56:05.725682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50b324dc058b'
down_revision = 'c943dd561f32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('telegram_chat_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'telegram_chat_id')
    # ### end Alembic commands ###
