"""Added telegram_chat_id to User model

Revision ID: debdee928ed6
Revises: 50b324dc058b
Create Date: 2025-02-12 02:39:30.846164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'debdee928ed6'
down_revision = '50b324dc058b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_choice', sa.Column('telegram_chat_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_choice', 'telegram_chat_id')
    # ### end Alembic commands ###
